#!/bin/bash

head $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS -c100| sha1sum | xargs wget -O "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS.srt" "http://www.libresubs.com:8080/latestLibresubs/download/?lang=pt_BR&id={}"
