#!/bin/sh
if ! [-f ~/.libreSubs/subFinder.jar]
then
	mkdir ~/.libreSubs
	wget "http://www.libresubs.com:8080/latestLibresubs/applets/subFinder.jar" -O ~/.libreSubs/subFinder.jar
fi

java -jar ~/.libreSubs/subFinder.jar "$@"